production:
  api_token: YJNG2JJ7EF9D04DOMTGE8T6ZC2TCZACD
  api_secret: L4BH67OEOPX8L8KKH9HTTSWMCFZH5H2BYS18FOUK
  id: APP-IYDQO7981OKQ
  access_token: 96236c8ce7944d80a98cf64ea7f3f2e5_v2
  secret: 071f4f6be2ca47e0bdc4f7d9242273f2
  redirect_uri: http://teste.ruaalecrim.com.br/auth/moip


